services:
  - type: web
    name: oce-web-tool
    env: docker
    region: oregon
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TESSDATA_PREFIX
        value: "/usr/share/tesseract-ocr/4.00/tessdata/"


