services:
  - type: web
    name: ocr-web-tool
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"

